# Discord
discord.bot.token=${DISCORD_BOT_TOKEN}
discord.application.id=${DISCORD_APPLICATION_ID}
discord.user.id=${DISCORD_USER_ID}
discord.client.secret=${DISCORD_CLIENT_SECRET}
discord.access.token=${DISCORD_ACCESS_TOKEN}

# Github
github.username=${GITHUB_USERNAME}
github.token=${GITHUB_TOKEN}
github.webhook.secret=${GITHUB_WEBHOOK_SECRET}

# Widget
widget.refresh.minutes=${WIDGET_REFRESH_MINUTES}
